---
ansible_host: "192.168.66.21"
ansible_ssh_private_key_file: /vagrant/.vagrant/machines/zabbix/virtualbox/private_key
ansible_python_interpreter: /usr/bin/python3.12
zabbix_api_user: "Admin"
zabbix_api_password: "zabbix"
