---
- name: Configure Zabbix server
  hosts: zabbix
  gather_facts: false
  vars:
    monitored_host_ip: "192.168.66.20"
    monitored_host_name: "app"
    zabbix_host_group: "Linux servers"
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_zabbix_url_path: ''
    ansible_user: "{{ zabbix_api_user }}"
    ansible_password: "{{ zabbix_api_password }}"
  tasks:
    # Note: Zabbix is already installed in the Vagrant box, we only have to add configuration to start monitoring.

    - name: Create host in Zabbix
      community.zabbix.zabbix_host:
        http_login_user: "{{ zabbix_api_user }}"
        http_login_password: "{{ zabbix_api_password }}"
        host_name: "{{ monitored_host_name }}"
        visible_name: "{{ monitored_host_name }}"
        description: Application server
        host_groups:
          - "{{ zabbix_host_group }}"
        link_templates:
          - Linux by Zabbix agent
          - ICMP Ping
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ monitored_host_ip }}"
            dns: ""
            port: 10050
        status: enabled

    # This collects data from the application log.
    # It only collects the lines that specify success or failure.
    - name: Create log monitoring item in Zabbix
      community.zabbix.zabbix_item:
        http_login_user: "{{ zabbix_api_user }}"
        http_login_password: "{{ zabbix_api_password }}"
        host_name: "{{ monitored_host_name }}"
        name: "App startup log monitor"
        params:
          # log requires zabbix_agent_active.
          type: zabbix_agent_active
          key: 'log[/var/log/app/app.log,"App successfully started|Error starting app",,,skip]'
          value_type: log
          interval: 5s
        state: present

    # This modifies the data collected by the log monitoring item to a simpler value ('successfully' or 'Error')
    # that can be triggered on.
    - name: Create dependent item to track last app startup status
      community.zabbix.zabbix_item:
        http_login_user: "{{ zabbix_api_user }}"
        http_login_password: "{{ zabbix_api_password }}"
        host_name: "{{ monitored_host_name }}"
        name: "App startup last status"
        params:
          type: dependent_item
          key: "app.status"
          master_item:
            item_name: "App startup log monitor"
          value_type: character
          preprocessing:
            - type: regular_expressions
              params: |-
                .*(successfully|Error).*
                \1
              error_handler: zabbix_server

    # This creates the actual error state on a dashboard.
    - name: Create trigger for app startup failure
      community.zabbix.zabbix_trigger:
        http_login_user: "{{ zabbix_api_user }}"
        http_login_password: "{{ zabbix_api_password }}"
        host_name: "{{ monitored_host_name }}"
        name: "App startup failure"
        description: "App last startup failed"
        params:
          severity: high
          expression: 'last(/{{ monitored_host_name }}/app.status)="Error"'
          status: enabled
        state: present
